//! The parser
//!
//! This is a module generated by the [`lalrpop`] library that parses the user input and returns an
//! [`ast`].
//!
//! The file from which this generated module came from is `src/parser/parser.lalrpop`.
//!
//! [`lalrpop`]: https://github.com/nikomatsakis/lalrpop/
//! [`ast`]: ../ast/index.html

#[allow(clippy)]
mod parser;
#[cfg(test)]
mod tests;

pub use self::parser::*;
